name: spy
description: "Die neue GIGA SPY APP"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+12

environment:
  sdk: '>=3.3.4 <4.0.0'

isar_version: 3.1.0

dependencies:
  flutter:
    sdk: flutter


  flutter_platform_widgets: ^7.0.0
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.6.0
  go_router: ^14.6.2
  shared_preferences: ^2.3.4
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  easy_localization: ^3.0.6
  flutter_launcher_icons: ^0.14.1
  fluttertoast: ^8.2.5
  swipable_stack: ^2.0.0
  flutter_timer_countdown: ^1.0.7
  flip_card: ^0.7.0
  appinio_swiper: ^2.1.1
  cloud_firestore: ^5.6.0
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  analyzer: ^6.7.0
  path_provider: ^2.1.3
  animated_custom_dropdown: ^3.1.1
  circular_countdown_timer: ^0.2.3
  custom_timer: ^0.2.3
  vibration: ^2.0.1
  url_launcher: ^6.3.1
  google_mobile_ads: ^5.2.0
  sqflite: ^2.4.0
  injectable: ^2.5.0
  get_it: ^8.0.2
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Freeman
      fonts:
        - asset: fonts/Lexend.ttf
          weight: 900

  assets:
    - images/app_logo.png
    - images/app_logo_with_font.png
    - assets/translations/
    - images/tap_hand2.png
    - images/swipe_hand.png
    - images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'images/app_logo.png'
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: '#000000'
  android_12:
    image: 'images/app_logo.png'
    color: '#000000'
  image: 'images/app_logo.png'

