// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeF6Zjpj-aJEBxgRSJ09g8xuvCYhe9_NA',
    appId: '1:818759423219:web:62a517c600dc640a39d386',
    messagingSenderId: '818759423219',
    projectId: 'spy-party-game',
    authDomain: 'spy-party-game.firebaseapp.com',
    databaseURL: 'https://spy-party-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spy-party-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBItmqcTrjLeqqUXf59E4hpJs5tfZxxtAI',
    appId: '1:818759423219:android:5603c1d71e3af7ce39d386',
    messagingSenderId: '818759423219',
    projectId: 'spy-party-game',
    databaseURL: 'https://spy-party-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spy-party-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDNoh17fVEkts6TQEIaK0-FuAk6dZCkM',
    appId: '1:818759423219:ios:fdff9d80c380a89039d386',
    messagingSenderId: '818759423219',
    projectId: 'spy-party-game',
    databaseURL: 'https://spy-party-game-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spy-party-game.appspot.com',
    iosBundleId: 'com.bykrisby.spy',
  );

}