Map<String, String> wordsEN = {
  '3M': 'Brand',
  'ABB': 'Brand',
  'Acer': 'Brand',
  'Adidas': 'Brand',
  'Adobe': 'Brand',
  'AIG': 'Brand',
  'Airbnb': 'Brand',
  'Air France': 'Brand',
  'Aldi': 'Brand',
  'Allianz': 'Brand',
  'Amazon': 'Brand',
  'AMD': 'Brand',
  'American Express': 'Brand',
  'Apple': 'Brand',
  'Ariel': 'Brand',
  'Asus': 'Brand',
  'AT&T': 'Brand',
  'Audi': 'Brand',
  'Axa': 'Brand',
  'Barbie': 'Brand',
  'Bank of America': 'Brand',
  'Best Buy': 'Brand',
  'Bic': 'Brand',
  'BMW': 'Brand',
  'Boston Consulting Group': 'Brand',
  'Bosch': 'Brand',
  'BP': 'Brand',
  'British Airways': 'Brand',
  'Burberry': 'Brand',
  'Burger King': 'Brand',
  'Canon': 'Brand',
  'Carrefour': 'Brand',
  'Caterpillar': 'Brand',
  'Chevron': 'Brand',
  'China Mobile': 'Brand',
  'Chanel': 'Brand',
  'Citibank': 'Brand',
  'Clorox': 'Brand',
  'Coca-Cola': 'Brand',
  'Colgate': 'Brand',
  'Costco': 'Brand',
  'Coursera': 'Brand',
  'Crocs': 'Brand',
  'Daimler': 'Brand',
  'Danone': 'Brand',
  'DB Schenker': 'Brand',
  'Dell': 'Brand',
  'Delta': 'Brand',
  'Deloitte': 'Brand',
  'Deutsche Bank': 'Brand',
  'Deutsche Telekom': 'Brand',
  'DHL': 'Brand',
  'Dior': 'Brand',
  'Disney': 'Brand',
  'Domino’s': 'Brand',
  'Dropbox': 'Brand',
  'Duolingo': 'Brand',
  'eBay': 'Brand',
  'EA Sports': 'Brand',
  'Emirates': 'Brand',
  'Epic Games': 'Brand',
  'Ernst & Young (EY)': 'Brand',
  'ExxonMobil': 'Brand',
  'Facebook': 'Brand',
  'Fairy': 'Brand',
  'FedEx': 'Brand',
  'Fendi': 'Brand',
  'Ferrari': 'Brand',
  'FIFA': 'Brand',
  'Fisher-Price': 'Brand',
  'Fitbit': 'Brand',
  'Ford': 'Brand',
  'Fujitsu': 'Brand',
  'Garmin': 'Brand',
  'Garnier': 'Brand',
  'GE (General Electric)': 'Brand',
  'Gillette': 'Brand',
  'GLS': 'Brand',
  'GoPro': 'Brand',
  'Google': 'Brand',
  'Gucci': 'Brand',
  'Head & Shoulders': 'Brand',
  'Heineken': 'Brand',
  'Hermès': 'Brand',
  'Honda': 'Brand',
  'Hot Wheels': 'Brand',
  'HP': 'Brand',
  'HSBC': 'Brand',
  'HTC': 'Brand',
  'Hugo Boss': 'Brand',
  'Hulu': 'Brand',
  'Huawei': 'Brand',
  'Hyundai': 'Brand',
  'IKEA': 'Brand',
  'IBM': 'Brand',
  'Instagram': 'Brand',
  'Intel': 'Brand',
  'IOC': 'Brand',
  'JBL': 'Brand',
  'Jeep': 'Brand',
  'JPMorgan Chase': 'Brand',
  'KFC': 'Brand',
  'Khan Academy': 'Brand',
  'Kia': 'Brand',
  'KPMG': 'Brand',
  'Lacoste': 'Brand',
  'Lamborghini': 'Brand',
  'Land Rover': 'Brand',
  'Lays': 'Brand',
  'Lego': 'Brand',
  'Lenovo': 'Brand',
  'Levi’s': 'Brand',
  'LG': 'Brand',
  'Lidl': 'Brand',
  'LinkedIn': 'Brand',
  'Louis Vuitton': 'Brand',
  'Lufthansa': 'Brand',
  'L’Oréal': 'Brand',
  'Lyft': 'Brand',
  'Maersk': 'Brand',
  'Mastercard': 'Brand',
  'Masimo': 'Brand',
  'Maserati': 'Brand',
  'Maybelline': 'Brand',
  'McDonald’s': 'Brand',
  'McKinsey & Company': 'Brand',
  'Mercedes-Benz': 'Brand',
  'Meta': 'Brand',
  'Microsoft': 'Brand',
  'Monster': 'Brand',
  'Mr. Proper': 'Brand',
  'Nescafé': 'Brand',
  'Nestlé': 'Brand',
  'Netflix': 'Brand',
  'New Balance': 'Brand',
  'Nike': 'Brand',
  'Nikon': 'Brand',
  'Nintendo': 'Brand',
  'Nivea': 'Brand',
  'Nokia': 'Brand',
  'Nutella': 'Brand',
  'Nvidia': 'Brand',
  'Olay': 'Brand',
  'Oracle': 'Brand',
  'Oral-B': 'Brand',
  'Pantene': 'Brand',
  'Paramount': 'Brand',
  'Patagonia': 'Brand',
  'PayPal': 'Brand',
  'Pepsi': 'Brand',
  'Persil': 'Brand',
  'Philips': 'Brand',
  'Pinterest': 'Brand',
  'Pixar': 'Brand',
  'Playmobil': 'Brand',
  'PlayStation': 'Brand',
  'Porsche': 'Brand',
  'Prada': 'Brand',
  'Pringles': 'Brand',
  'Procter & Gamble': 'Brand',
  'Puma': 'Brand',
  'PwC': 'Brand',
  'Qatar Airways': 'Brand',
  'Ralph Lauren': 'Brand',
  'Red Bull': 'Brand',
  'Reddit': 'Brand',
  'Reebok': 'Brand',
  'Revolut': 'Brand',
  'Ryanair': 'Brand',
  'Rolex': 'Brand',
  'Rockstar Games': 'Brand',
  'Samsung': 'Brand',
  'SAP': 'Brand',
  'Sharpie': 'Brand',
  'Shell': 'Brand',
  'Siemens': 'Brand',
  'Skechers': 'Brand',
  'Skype': 'Brand',
  'Slack': 'Brand',
  'Snapchat': 'Brand',
  'Sony': 'Brand',
  'Sony Pictures': 'Brand',
  'SpaceX': 'Brand',
  'Spotify': 'Brand',
  'Sprite': 'Brand',
  'Steam': 'Brand',
  'Subaru': 'Brand',
  'Subway': 'Brand',
  'Swatch': 'Brand',
  'Swiffer': 'Brand',
  'Target': 'Brand',
  'TCL': 'Brand',
  'Telegram': 'Brand',
  'Tesla': 'Brand',
  'Tesla Energy': 'Brand',
  'The North Face': 'Brand',
  'TikTok': 'Brand',
  'Tinder': 'Brand',
  'T-Mobile': 'Brand',
  'Toyota': 'Brand',
  'TripAdvisor': 'Brand',
  'TNT': 'Brand',
  'Turkish Airlines': 'Brand',
  'Twitter (X)': 'Brand',
  'Uber': 'Brand',
  'UEFA': 'Brand',
  'Uniqlo': 'Brand',
  'United Airlines': 'Brand',
  'UPS': 'Brand',
  'Vans': 'Brand',
  'Verizon': 'Brand',
  'Versace': 'Brand',
  'Visa': 'Brand',
  'Vodafone': 'Brand',
  'Volkswagen': 'Brand',
  'Volvo': 'Brand',
  'Walmart': 'Brand',
  'Warner Bros.': 'Brand',
  'WhatsApp': 'Brand',
  'Wix': 'Brand',
  'WordPress': 'Brand',
  'WWE': 'Brand',
  'Xbox': 'Brand',
  'Xiaomi': 'Brand',
  'YouTube': 'Brand',
  'Zalando': 'Brand',
  'Zara': 'Brand',
  'Zoom': 'Brand',
  'Zurich': 'Brand',
  'Doctor': 'Occupations',
  'Teacher': 'Occupations',
  'Police officer': 'Occupations',
  'Firefighter': 'Occupations',
  'Baker': 'Occupations',
  'Cook': 'Occupations',
  'Waiter': 'Occupations',
  'Hairdresser': 'Occupations',
  'Painter': 'Occupations',
  'Carpenter': 'Occupations',
  'Gardener': 'Occupations',
  'Salesperson': 'Occupations',
  'Bus driver': 'Occupations',
  'Pilot': 'Occupations',
  'Nurse': 'Occupations',
  'Pharmacist': 'Occupations',
  'Lawyer': 'Occupations',
  'Judge': 'Occupations',
  'Architect': 'Occupations',
  'Journalist': 'Occupations',
  'Photographer': 'Occupations',
  'Musician': 'Occupations',
  'Actor': 'Occupations',
  'Dancer': 'Occupations',
  'Cabinet maker': 'Occupations',
  'Butcher': 'Occupations',
  'Mail carrier': 'Occupations',
  'Bank clerk': 'Occupations',
  'Insurance agent': 'Occupations',
  'Real estate agent': 'Occupations',
  'Librarian': 'Occupations',
  'Accountant': 'Occupations',
  'Secretary': 'Occupations',
  'Mechanic': 'Occupations',
  'Electrician': 'Occupations',
  'Plumber': 'Occupations',
  'Bricklayer': 'Occupations',
  'Tile setter': 'Occupations',
  'Roofer': 'Occupations',
  'Farmer': 'Occupations',
  'Veterinarian': 'Occupations',
  'Social worker': 'Occupations',
  'Educator': 'Occupations',
  'Physical therapist': 'Occupations',
  'Occupational therapist': 'Occupations',
  'Speech therapist': 'Occupations',
  'Psychologist': 'Occupations',
  'Sports teacher': 'Occupations',
  'Fitness trainer': 'Occupations',
  'Beautician': 'Occupations',
  'Optician': 'Occupations',
  'Dentist': 'Occupations',
  'Midwife': 'Occupations',
  'Train driver': 'Occupations',
  'Ship captain': 'Occupations',
  'Flight attendant': 'Occupations',
  'Taxi driver': 'Occupations',
  'Garbage collector': 'Occupations',
  'Cleaner': 'Occupations',
  'Soldier': 'Occupations',
  'Chef': 'Occupations',
  'Cashier': 'Occupations',
  'Receptionist': 'Occupations',
  'Graphic designer': 'Occupations',
  'Web designer': 'Occupations',
  'Programmer': 'Occupations',
  'Computer scientist': 'Occupations',
  'Human resources manager': 'Occupations',
  'Marketing manager': 'Occupations',
  'Event manager': 'Occupations',
  'Tour guide': 'Occupations',
  'Interpreter': 'Occupations',
  'Translator': 'Occupations',
  'Detective': 'Occupations',
  'Funeral director': 'Occupations',
  'Florist': 'Occupations',
  'Goldsmith': 'Occupations',
  'Watchmaker': 'Occupations',
  'Shoemaker': 'Occupations',
  'Interior decorator': 'Occupations',
  'Glassblower': 'Occupations',
  'Ceramicist': 'Occupations',
  'Sculptor': 'Occupations',
  'Stonemason': 'Occupations',
  'Bookbinder': 'Occupations',
  'Sound technician': 'Occupations',
  'Set designer': 'Occupations',
  'Director': 'Occupations',
  'Cameraman': 'Occupations',
  'Make-up artist': 'Occupations',
  'DJ': 'Occupations',
  'Producer': 'Occupations',
  'Composer': 'Occupations',
  'Conductor': 'Occupations',
  'Singer': 'Occupations',
  'Author': 'Occupations',
  'Editor': 'Occupations',
  'Proofreader': 'Occupations',
  'Illustrator': 'Occupations',
  'Cartoonist': 'Occupations',
  'Tattoo artist': 'Occupations',
  'Piercer': 'Occupations',
  'Fashion designer': 'Occupations',
  'Tailor': 'Occupations',
  'Jeweler': 'Occupations',
  'Winemaker': 'Occupations',
  'Brewer': 'Occupations',
  'Miller': 'Occupations',
  'Fisherman': 'Occupations',
  'Miner': 'Occupations',
  'Astronaut': 'Occupations',
  'Chemist': 'Occupations',
  'Physicist': 'Occupations',
  'Biologist': 'Occupations',
  'Geologist': 'Occupations',
  'Environmentalist': 'Occupations',
  'Archaeologist': 'Occupations',
  'Historian': 'Occupations',
  'Philosopher': 'Occupations',
  'Politician': 'Occupations',
  'Diplomat': 'Occupations',
  'Prosecutor': 'Occupations',
  'Notary': 'Occupations',
  'Tax advisor': 'Occupations',
  'Auditor': 'Occupations',
  'Management consultant': 'Occupations',
  'Analyst': 'Occupations',
  'Controller': 'Occupations',
  'Logistics specialist': 'Occupations',
  'Forwarding agent': 'Occupations',
  'Customs officer': 'Occupations',
  'Police dog trainer': 'Occupations',
  'Pyrotechnician': 'Occupations',
  'Glazier': 'Occupations',
  'Scaffolder': 'Occupations',
  'Road construction worker': 'Occupations',
  'Civil engineer': 'Occupations',
  'Surveyor': 'Occupations',
  'Laboratory technician': 'Occupations',
  'Physics laboratory technician': 'Occupations',
  'Chemistry laboratory technician': 'Occupations',
  'Biology laboratory technician': 'Occupations',
  'Radiologist': 'Occupations',
  'Anesthesiologist': 'Occupations',
  'Surgeon': 'Occupations',
  'Orthopedic surgeon': 'Occupations',
  'Cardiologist': 'Occupations',
  'Dermatologist': 'Occupations',
  'Pediatrician': 'Occupations',
  'Psychiatrist': 'Occupations',
  'Urologist': 'Occupations',
  'Gynecologist': 'Occupations',
  'Neurologist': 'Occupations',
  'Oncologist': 'Occupations',
  'Ophthalmologist': 'Occupations',
  'Otorhinolaryngologist': 'Occupations',
  'Dental technician': 'Occupations',
  'Podiatrist': 'Occupations',
  'Orthopedic shoemaker': 'Occupations',
  'Star Wars': 'Movies/Series',
  'The Godfather': 'Movies/Series',
  'Titanic': 'Movies/Series',
  'Harry Potter': 'Movies/Series',
  'The Lord of the Rings': 'Movies/Series',
  'E.T. the Extra-Terrestrial': 'Movies/Series',
  'Jurassic Park': 'Movies/Series',
  'Avatar': 'Movies/Series',
  'Avengers: Endgame': 'Movies/Series',
  'Gone with the Wind': 'Movies/Series',
  'Casablanca': 'Movies/Series',
  'The Wizard of Oz': 'Movies/Series',
  'Psycho': 'Movies/Series',
  '2001: A Space Odyssey': 'Movies/Series',
  'Back to the Future': 'Movies/Series',
  'Pulp Fiction': 'Movies/Series',
  'Forrest Gump': 'Movies/Series',
  'The Matrix': 'Movies/Series',
  'Inception': 'Movies/Series',
  'Interstellar': 'Movies/Series',
  'Fight Club': 'Movies/Series',
  'The Silence of the Lambs': 'Movies/Series',
  'Schindler\'s List': 'Movies/Series',
  'The Shawshank Redemption': 'Movies/Series',
  'Seven': 'Movies/Series',
  'Goodfellas': 'Movies/Series',
  'The Lion King': 'Movies/Series',
  'Finding Nemo': 'Movies/Series',
  'Toy Story': 'Movies/Series',
  'Frozen': 'Movies/Series',
  'Minions': 'Movies/Series',
  'Shrek': 'Movies/Series',
  'Mickey Mouse': 'Movies/Series',
  'Donald Duck': 'Movies/Series',
  'SpongeBob SquarePants': 'Movies/Series',
  'The Simpsons': 'Movies/Series',
  'Family Guy': 'Movies/Series',
  'South Park': 'Movies/Series',
  'Breaking Bad': 'Movies/Series',
  'Game of Thrones': 'Movies/Series',
  'Friends': 'Movies/Series',
  'The Big Bang Theory': 'Movies/Series',
  'How I Met Your Mother': 'Movies/Series',
  'The Office': 'Movies/Series',
  'Stranger Things': 'Movies/Series',
  'Squid Game': 'Movies/Series',
  'The Crown': 'Movies/Series',
  'Sherlock': 'Movies/Series',
  'House': 'Movies/Series',
  'Grey\'s Anatomy': 'Movies/Series',
  'ER': 'Movies/Series',
  'Lost': 'Movies/Series',
  'The X-Files': 'Movies/Series',
  'Miami Vice': 'Movies/Series',
  'Magnum, P.I.': 'Movies/Series',
  'Knight Rider': 'Movies/Series',
  'Dallas': 'Movies/Series',
  'Dynasty': 'Movies/Series',
  'Falcon Crest': 'Movies/Series',
  'Good Times, Bad Times': 'Movies/Series',
  'Crime Scene': 'Movies/Series',
  'Police Call 110': 'Movies/Series',
  'Inspector Rex': 'Movies/Series',
  'Derrick': 'Movies/Series',
  'The Fall Guy': 'Movies/Series',
  'MacGyver': 'Movies/Series',
  'The A-Team': 'Movies/Series',
  'Baywatch': 'Movies/Series',
  'Beverly Hills, 90210': 'Movies/Series',
  'Melrose Place': 'Movies/Series',
  'Sex and the City': 'Movies/Series',
  'Desperate Housewives': 'Movies/Series',
  'Gossip Girl': 'Movies/Series',
  'One Tree Hill': 'Movies/Series',
  'The O.C.': 'Movies/Series',
  'Dawson\'s Creek': 'Movies/Series',
  'Buffy the Vampire Slayer': 'Movies/Series',
  'Charmed': 'Movies/Series',
  'Smallville': 'Movies/Series',
  'Supernatural': 'Movies/Series',
  'The Vampire Diaries': 'Movies/Series',
  'Pretty Little Liars': 'Movies/Series',
  'Gilmore Girls': 'Movies/Series',
  'Ally McBeal': 'Movies/Series',
  'Seinfeld': 'Movies/Series',
  'Frasier': 'Movies/Series',
  'Cheers': 'Movies/Series',
  'MAS*H': 'Movies/Series',
  'I Love Lucy': 'Movies/Series',
  'The Addams Family': 'Movies/Series',
  'The Munsters': 'Movies/Series',
  'I Dream of Jeannie': 'Movies/Series',
  'Bewitched': 'Movies/Series',
  'Bonanza': 'Movies/Series',
  'Gunsmoke': 'Movies/Series',
  'Star Trek': 'Movies/Series',
  'Babylon 5': 'Movies/Series',
  'Battlestar Galactica': 'Movies/Series',
  'Doctor Who': 'Movies/Series',
  'Sherlock Holmes': 'Movies/Series',
  'James Bond': 'Movies/Series',
  'Indiana Jones': 'Movies/Series',
  'Mission: Impossible': 'Movies/Series',
  'Rocky': 'Movies/Series',
  'Rambo': 'Movies/Series',
  'Terminator': 'Movies/Series',
  'Alien': 'Movies/Series',
  'Predator': 'Movies/Series',
  'Pirates of the Caribbean': 'Movies/Series',
  'Fast & Furious': 'Movies/Series',
  'The Empire Strikes Back': 'Movies/Series',
  'The Dark Knight': 'Movies/Series',
  'Good Will Hunting': 'Movies/Series',
  'One Flew Over the Cuckoo\'s Nest': 'Movies/Series',
  'Life Is Beautiful': 'Movies/Series',
  'Saving Private Ryan': 'Movies/Series',
  'Gladiator': 'Movies/Series',
  'Braveheart': 'Movies/Series',
  'The Exorcist': 'Movies/Series',
  'The Shining': 'Movies/Series',
  'Halloween': 'Movies/Series',
  'A Nightmare on Elm Street': 'Movies/Series',
  'Friday the 13th': 'Movies/Series',
  'Saw': 'Movies/Series',
  'Jaws': 'Movies/Series',
  'Rear Window': 'Movies/Series',
  'Vertigo': 'Movies/Series',
  'The Birds': 'Movies/Series',
  'Lawrence of Arabia': 'Movies/Series',
  'Ben-Hur': 'Movies/Series',
  'Cleopatra': 'Movies/Series',
  'Spartacus': 'Movies/Series',
  'West Side Story': 'Movies/Series',
  'Mary Poppins': 'Movies/Series',
  'The Sound of Music': 'Movies/Series',
  'Grease': 'Movies/Series',
  'Dirty Dancing': 'Movies/Series',
  'Flashdance': 'Movies/Series',
  'Footloose': 'Movies/Series',
  'Saturday Night Fever': 'Movies/Series',
  'Staying Alive': 'Movies/Series',
  'Fame': 'Movies/Series',
  'A Star Is Born': 'Movies/Series',
  'Moulin Rouge!': 'Movies/Series',
  'La La Land': 'Movies/Series',
  'Chicago': 'Movies/Series',
  'Cabaret': 'Movies/Series',
  'My Fair Lady': 'Movies/Series',
  'Singin\' in the Rain': 'Movies/Series',
  'They Call Me Trinity': 'Movies/Series',
  'The Good, the Bad and the Ugly': 'Movies/Series',
  'Once Upon a Time in the West': 'Movies/Series',
  'A Fistful of Dollars': 'Movies/Series',
  'Dances with Wolves': 'Movies/Series',
  'Unforgiven': 'Movies/Series',
  'High Noon': 'Movies/Series',
  'Shane': 'Movies/Series',
  'Rio Bravo': 'Movies/Series',
  'The Wild Wild West': 'Movies/Series',
  'Winnetou': 'Movies/Series',
  'Old Shatterhand': 'Movies/Series',
  'The Olsen Gang': 'Movies/Series',
  'Asterix and Obelix': 'Movies/Series',
  'Lucky Luke': 'Movies/Series',
  'The Smurfs': 'Movies/Series',
  'Maya the Bee': 'Movies/Series',
  'Heidi': 'Movies/Series',
  'Pinocchio': 'Movies/Series',
  'The Jungle Book': 'Movies/Series',
  'Cinderella': 'Movies/Series',
  'Snow White and the Seven Dwarfs': 'Movies/Series',
  'Sleeping Beauty': 'Movies/Series',
  'The Little Mermaid': 'Movies/Series',
  'Beauty and the Beast': 'Movies/Series',
  'Aladdin': 'Movies/Series',
  'Mulan': 'Movies/Series',
  'Pocahontas': 'Movies/Series',
  'Tarzan': 'Movies/Series',
  'Cars': 'Movies/Series',
  'Ratatouille': 'Movies/Series',
  'WALL-E': 'Movies/Series',
  'Up': 'Movies/Series',
  'Inside Out': 'Movies/Series',
  'Coco': 'Movies/Series',
  'Spirited Away': 'Movies/Series',
  'My Neighbor Totoro': 'Movies/Series',
  'Princess Mononoke': 'Movies/Series',
  'Howl\'s Moving Castle': 'Movies/Series',
  'Akira': 'Movies/Series',
  'Dragon Ball': 'Movies/Series',
  'Sailor Moon': 'Movies/Series',
  'Pokémon': 'Movies/Series',
  'Neon Genesis Evangelion': 'Movies/Series',
  'One Piece': 'Movies/Series',
  'Naruto': 'Movies/Series',
  'Attack on Titan': 'Movies/Series',
  'Albert Einstein': 'Famous Personality',
  'Leonardo da Vinci': 'Famous Personality',
  'William Shakespeare': 'Famous Personality',
  'Mahatma Gandhi': 'Famous Personality',
  'Nelson Mandela': 'Famous Personality',
  'Marilyn Monroe': 'Famous Personality',
  'Winston Churchill': 'Famous Personality',
  'Isaac Newton': 'Famous Personality',
  'Martin Luther King Jr.': 'Famous Personality',
  'Steve Jobs': 'Famous Personality',
  'Michael Jackson': 'Famous Personality',
  'Elvis Presley': 'Famous Personality',
  'Charles Darwin': 'Famous Personality',
  'Julius Caesar': 'Famous Personality',
  'Napoleon Bonaparte': 'Famous Personality',
  'Alexander the Great': 'Famous Personality',
  'Muhammad Ali': 'Famous Personality',
  'Queen Elizabeth II': 'Famous Personality',
  'Marie Curie': 'Famous Personality',
  'Nikola Tesla': 'Famous Personality',
  'Stephen Hawking': 'Famous Personality',
  'Oprah Winfrey': 'Famous Personality',
  'Mother Teresa': 'Famous Personality',
  'Sigmund Freud': 'Famous Personality',
  'Pablo Picasso': 'Famous Personality',
  'Vincent van Gogh': 'Famous Personality',
  'Ludwig van Beethoven': 'Famous Personality',
  'Wolfgang Amadeus Mozart': 'Famous Personality',
  'Frida Kahlo': 'Famous Personality',
  'Mark Twain': 'Famous Personality',
  'J.K. Rowling': 'Famous Personality',
  'George Washington': 'Famous Personality',
  'Abraham Lincoln': 'Famous Personality',
  'Franklin D. Roosevelt': 'Famous Personality',
  'John F. Kennedy': 'Famous Personality',
  'Barack Obama': 'Famous Personality',
  'Donald Trump': 'Famous Personality',
  'Joe Biden': 'Famous Personality',
  'Adolf Hitler': 'Famous Personality',
  'Joseph Stalin': 'Famous Personality',
  'Vladimir Putin': 'Famous Personality',
  'Mao Zedong': 'Famous Personality',
  'Kim Jong-un': 'Famous Personality',
  'Che Guevara': 'Famous Personality',
  'Fidel Castro': 'Famous Personality',
  'Dalai Lama': 'Famous Personality',
  'Pope Francis': 'Famous Personality',
  'Jesus Christ': 'Famous Personality',
  'Buddha': 'Famous Personality',
  'Confucius': 'Famous Personality',
  'Muhammad': 'Famous Personality',
  'Socrates': 'Famous Personality',
  'Plato': 'Famous Personality',
  'Aristotle': 'Famous Personality',
  'Galileo Galilei': 'Famous Personality',
  'Marco Polo': 'Famous Personality',
  'Christopher Columbus': 'Famous Personality',
  'Ferdinand Magellan': 'Famous Personality',
  'Neil Armstrong': 'Famous Personality',
  'Buzz Aldrin': 'Famous Personality',
  'Yuri Gagarin': 'Famous Personality',
  'Elon Musk': 'Famous Personality',
  'Jeff Bezos': 'Famous Personality',
  'Mark Zuckerberg': 'Famous Personality',
  'Bill Gates': 'Famous Personality',
  'Warren Buffett': 'Famous Personality',
  'Richard Branson': 'Famous Personality',
  'Walt Disney': 'Famous Personality',
  'Stan Lee': 'Famous Personality',
  'Bruce Lee': 'Famous Personality',
  'Jackie Chan': 'Famous Personality',
  'Tom Cruise': 'Famous Personality',
  'Leonardo DiCaprio': 'Famous Personality',
  'Brad Pitt': 'Famous Personality',
  'Angelina Jolie': 'Famous Personality',
  'Jennifer Aniston': 'Famous Personality',
  'Keanu Reeves': 'Famous Personality',
  'Dwayne Johnson': 'Famous Personality',
  'Will Smith': 'Famous Personality',
  'Robert Downey Jr.': 'Famous Personality',
  'Johnny Depp': 'Famous Personality',
  'Clint Eastwood': 'Famous Personality',
  'Meryl Streep': 'Famous Personality',
  'Audrey Hepburn': 'Famous Personality',
  'Charlie Chaplin': 'Famous Personality',
  'Frodo Baggins': 'Famous Personality',
  'Darth Vader': 'Famous Personality',
  'Yoda': 'Famous Personality',
  'Luke Skywalker': 'Famous Personality',
  'Batman': 'Famous Personality',
  'Superman': 'Famous Personality',
  'Wonder Woman': 'Famous Personality',
  'Spider-Man': 'Famous Personality',
  'Iron Man': 'Famous Personality',
  'Hulk': 'Famous Personality',
  'Captain America': 'Famous Personality',
  'Queen Victoria': 'Famous Personality',
};
