Map<String, String> wordsDe = {
  '3M': 'Marke',
  'ABB': 'Marke',
  'Acer': 'Marke',
  'Adidas': 'Marke',
  'Adobe': 'Marke',
  'AIG': 'Marke',
  'Airbnb': 'Marke',
  'Air France': 'Marke',
  'Aldi': 'Marke',
  'Allianz': 'Marke',
  'Amazon': 'Marke',
  'AMD': 'Marke',
  'American Express': 'Marke',
  'Apple': 'Marke',
  'Ariel': 'Marke',
  'Asus': 'Marke',
  'AT&T': 'Marke',
  'Audi': 'Marke',
  'Axa': 'Marke',
  'Barbie': 'Marke',
  'Bank of America': 'Marke',
  'Best Buy': 'Marke',
  'Bic': 'Marke',
  'BMW': 'Marke',
  'Boston Consulting Group': 'Marke',
  'Bosch': 'Marke',
  'BP': 'Marke',
  'British Airways': 'Marke',
  'Burberry': 'Marke',
  'Burger King': 'Marke',
  'Canon': 'Marke',
  'Carrefour': 'Marke',
  'Caterpillar': 'Marke',
  'Chevron': 'Marke',
  'China Mobile': 'Marke',
  'Chanel': 'Marke',
  'Citibank': 'Marke',
  'Clorox': 'Marke',
  'Coca-Cola': 'Marke',
  'Colgate': 'Marke',
  'Costco': 'Marke',
  'Coursera': 'Marke',
  'Crocs': 'Marke',
  'Daimler': 'Marke',
  'Danone': 'Marke',
  'DB Schenker': 'Marke',
  'Dell': 'Marke',
  'Delta': 'Marke',
  'Deloitte': 'Marke',
  'Deutsche Bank': 'Marke',
  'Deutsche Telekom': 'Marke',
  'DHL': 'Marke',
  'Dior': 'Marke',
  'Disney': 'Marke',
  'Domino’s': 'Marke',
  'Dropbox': 'Marke',
  'Duolingo': 'Marke',
  'eBay': 'Marke',
  'EA Sports': 'Marke',
  'Emirates': 'Marke',
  'Epic Games': 'Marke',
  'Ernst & Young (EY)': 'Marke',
  'ExxonMobil': 'Marke',
  'Facebook': 'Marke',
  'Fairy': 'Marke',
  'FedEx': 'Marke',
  'Fendi': 'Marke',
  'Ferrari': 'Marke',
  'FIFA': 'Marke',
  'Fisher-Price': 'Marke',
  'Fitbit': 'Marke',
  'Ford': 'Marke',
  'Fujitsu': 'Marke',
  'Garmin': 'Marke',
  'Garnier': 'Marke',
  'GE (General Electric)': 'Marke',
  'Gillette': 'Marke',
  'GLS': 'Marke',
  'GoPro': 'Marke',
  'Google': 'Marke',
  'Gucci': 'Marke',
  'Head & Shoulders': 'Marke',
  'Heineken': 'Marke',
  'Hermès': 'Marke',
  'Honda': 'Marke',
  'Hot Wheels': 'Marke',
  'HP': 'Marke',
  'HSBC': 'Marke',
  'HTC': 'Marke',
  'Hugo Boss': 'Marke',
  'Hulu': 'Marke',
  'Huawei': 'Marke',
  'Hyundai': 'Marke',
  'IKEA': 'Marke',
  'IBM': 'Marke',
  'Instagram': 'Marke',
  'Intel': 'Marke',
  'IOC': 'Marke',
  'JBL': 'Marke',
  'Jeep': 'Marke',
  'JPMorgan Chase': 'Marke',
  'KFC': 'Marke',
  'Khan Academy': 'Marke',
  'Kia': 'Marke',
  'KPMG': 'Marke',
  'Lacoste': 'Marke',
  'Lamborghini': 'Marke',
  'Land Rover': 'Marke',
  'Lays': 'Marke',
  'Lego': 'Marke',
  'Lenovo': 'Marke',
  'Levi’s': 'Marke',
  'LG': 'Marke',
  'Lidl': 'Marke',
  'LinkedIn': 'Marke',
  'Louis Vuitton': 'Marke',
  'Lufthansa': 'Marke',
  'L’Oréal': 'Marke',
  'Lyft': 'Marke',
  'Maersk': 'Marke',
  'Mastercard': 'Marke',
  'Masimo': 'Marke',
  'Maserati': 'Marke',
  'Maybelline': 'Marke',
  'McDonald’s': 'Marke',
  'McKinsey & Company': 'Marke',
  'Mercedes-Benz': 'Marke',
  'Meta': 'Marke',
  'Microsoft': 'Marke',
  'Monster': 'Marke',
  'Mr. Proper': 'Marke',
  'Nescafé': 'Marke',
  'Nestlé': 'Marke',
  'Netflix': 'Marke',
  'New Balance': 'Marke',
  'Nike': 'Marke',
  'Nikon': 'Marke',
  'Nintendo': 'Marke',
  'Nivea': 'Marke',
  'Nokia': 'Marke',
  'Nutella': 'Marke',
  'Nvidia': 'Marke',
  'Olay': 'Marke',
  'Oracle': 'Marke',
  'Oral-B': 'Marke',
  'Pantene': 'Marke',
  'Paramount': 'Marke',
  'Patagonia': 'Marke',
  'PayPal': 'Marke',
  'Pepsi': 'Marke',
  'Persil': 'Marke',
  'Philips': 'Marke',
  'Pinterest': 'Marke',
  'Pixar': 'Marke',
  'Playmobil': 'Marke',
  'PlayStation': 'Marke',
  'Porsche': 'Marke',
  'Prada': 'Marke',
  'Pringles': 'Marke',
  'Procter & Gamble': 'Marke',
  'Puma': 'Marke',
  'PwC': 'Marke',
  'Qatar Airways': 'Marke',
  'Ralph Lauren': 'Marke',
  'Red Bull': 'Marke',
  'Reddit': 'Marke',
  'Reebok': 'Marke',
  'Revolut': 'Marke',
  'Ryanair': 'Marke',
  'Rolex': 'Marke',
  'Rockstar Games': 'Marke',
  'Samsung': 'Marke',
  'SAP': 'Marke',
  'Sharpie': 'Marke',
  'Shell': 'Marke',
  'Siemens': 'Marke',
  'Skechers': 'Marke',
  'Skype': 'Marke',
  'Slack': 'Marke',
  'Snapchat': 'Marke',
  'Sony': 'Marke',
  'Sony Pictures': 'Marke',
  'SpaceX': 'Marke',
  'Spotify': 'Marke',
  'Sprite': 'Marke',
  'Steam': 'Marke',
  'Subaru': 'Marke',
  'Subway': 'Marke',
  'Swatch': 'Marke',
  'Swiffer': 'Marke',
  'Target': 'Marke',
  'TCL': 'Marke',
  'Telegram': 'Marke',
  'Tesla': 'Marke',
  'Tesla Energy': 'Marke',
  'The North Face': 'Marke',
  'TikTok': 'Marke',
  'Tinder': 'Marke',
  'T-Mobile': 'Marke',
  'Toyota': 'Marke',
  'TripAdvisor': 'Marke',
  'TNT': 'Marke',
  'Turkish Airlines': 'Marke',
  'Twitter (X)': 'Marke',
  'Uber': 'Marke',
  'UEFA': 'Marke',
  'Uniqlo': 'Marke',
  'United Airlines': 'Marke',
  'UPS': 'Marke',
  'Vans': 'Marke',
  'Verizon': 'Marke',
  'Versace': 'Marke',
  'Visa': 'Marke',
  'Vodafone': 'Marke',
  'Volkswagen': 'Marke',
  'Volvo': 'Marke',
  'Walmart': 'Marke',
  'Warner Bros.': 'Marke',
  'WhatsApp': 'Marke',
  'Wix': 'Marke',
  'WordPress': 'Marke',
  'WWE': 'Marke',
  'Xbox': 'Marke',
  'Xiaomi': 'Marke',
  'YouTube': 'Marke',
  'Zalando': 'Marke',
  'Zara': 'Marke',
  'Zoom': 'Marke',
  'Zurich': 'Marke',
  'Arzt': 'Berufe',
  'Lehrer': 'Berufe',
  'Polizist': 'Berufe',
  'Feuerwehrmann': 'Berufe',
  'Bäcker': 'Berufe',
  'Koch': 'Berufe',
  'Kellner': 'Berufe',
  'Friseur': 'Berufe',
  'Maler': 'Berufe',
  'Zimmermann': 'Berufe',
  'Gärtner': 'Berufe',
  'Verkäufer': 'Berufe',
  'Busfahrer': 'Berufe',
  'Pilot': 'Berufe',
  'Krankenschwester': 'Berufe',
  'Apotheker': 'Berufe',
  'Anwalt': 'Berufe',
  'Richter': 'Berufe',
  'Architekt': 'Berufe',
  'Journalist': 'Berufe',
  'Fotograf': 'Berufe',
  'Musiker': 'Berufe',
  'Schauspieler': 'Berufe',
  'Tänzer': 'Berufe',
  'Schreiner': 'Berufe',
  'Metzger': 'Berufe',
  'Postbote': 'Berufe',
  'Bankangestellter': 'Berufe',
  'Versicherungsvertreter': 'Berufe',
  'Immobilienmakler': 'Berufe',
  'Bibliothekar': 'Berufe',
  'Buchhalter': 'Berufe',
  'Sekretärin': 'Berufe',
  'Mechaniker': 'Berufe',
  'Elektriker': 'Berufe',
  'Klempner': 'Berufe',
  'Maurer': 'Berufe',
  'Fliesenleger': 'Berufe',
  'Dachdecker': 'Berufe',
  'Landwirt': 'Berufe',
  'Tierarzt': 'Berufe',
  'Sozialarbeiter': 'Berufe',
  'Erzieher': 'Berufe',
  'Physiotherapeut': 'Berufe',
  'Ergotherapeut': 'Berufe',
  'Logopäde': 'Berufe',
  'Psychologe': 'Berufe',
  'Sportlehrer': 'Berufe',
  'Fitnesstrainer': 'Berufe',
  'Kosmetiker': 'Berufe',
  'Optiker': 'Berufe',
  'Zahnarzt': 'Berufe',
  'Hebamme': 'Berufe',
  'Lokführer': 'Berufe',
  'Schiffsführer': 'Berufe',
  'Flugbegleiter': 'Berufe',
  'Taxifahrer': 'Berufe',
  'Müllmann': 'Berufe',
  'Reinigungskraft': 'Berufe',
  'Soldat': 'Berufe',
  'Kassierer': 'Berufe',
  'Empfangsmitarbeiter': 'Berufe',
  'Grafikdesigner': 'Berufe',
  'Webdesigner': 'Berufe',
  'Programmierer': 'Berufe',
  'Informatiker': 'Berufe',
  'Personalchef': 'Berufe',
  'Marketing Manager': 'Berufe',
  'Eventmanager': 'Berufe',
  'Reiseleiter': 'Berufe',
  'Dolmetscher': 'Berufe',
  'Übersetzer': 'Berufe',
  'Detektiv': 'Berufe',
  'Bestatter': 'Berufe',
  'Florist': 'Berufe',
  'Goldschmied': 'Berufe',
  'Uhrmacher': 'Berufe',
  'Schuhmacher': 'Berufe',
  'Raumausstatter': 'Berufe',
  'Glasbläser': 'Berufe',
  'Keramiker': 'Berufe',
  'Bildhauer': 'Berufe',
  'Steinmetz': 'Berufe',
  'Buchbinder': 'Berufe',
  'Tontechniker': 'Berufe',
  'Bühnenbildner': 'Berufe',
  'Regisseur': 'Berufe',
  'Kameramann': 'Berufe',
  'Maskenbildner': 'Berufe',
  'DJ': 'Berufe',
  'Produzent': 'Berufe',
  'Komponist': 'Berufe',
  'Dirigent': 'Berufe',
  'Sänger': 'Berufe',
  'Autor': 'Berufe',
  'Redakteur': 'Berufe',
  'Lektor': 'Berufe',
  'Illustrator': 'Berufe',
  'Cartoonist': 'Berufe',
  'Tätowierer': 'Berufe',
  'Piercer': 'Berufe',
  'Modedesigner': 'Berufe',
  'Schneider': 'Berufe',
  'Juwelier': 'Berufe',
  'Winzer': 'Berufe',
  'Brauer': 'Berufe',
  'Müller': 'Berufe',
  'Fischer': 'Berufe',
  'Bergmann': 'Berufe',
  'Astronaut': 'Berufe',
  'Chemiker': 'Berufe',
  'Physiker': 'Berufe',
  'Biologe': 'Berufe',
  'Geologe': 'Berufe',
  'Umweltschützer': 'Berufe',
  'Archäologe': 'Berufe',
  'Historiker': 'Berufe',
  'Philosoph': 'Berufe',
  'Politiker': 'Berufe',
  'Diplomat': 'Berufe',
  'Staatsanwalt': 'Berufe',
  'Notar': 'Berufe',
  'Steuerberater': 'Berufe',
  'Wirtschaftsprüfer': 'Berufe',
  'Unternehmensberater': 'Berufe',
  'Analyst': 'Berufe',
  'Controller': 'Berufe',
  'Logistiker': 'Berufe',
  'Spediteur': 'Berufe',
  'Zöllner': 'Berufe',
  'Polizeihundetrainer': 'Berufe',
  'Feuerwerksmeister': 'Berufe',
  'Glaser': 'Berufe',
  'Gerüstbauer': 'Berufe',
  'Straßenbauer': 'Berufe',
  'Tiefbauer': 'Berufe',
  'Vermessungstechniker': 'Berufe',
  'Laborant': 'Berufe',
  'Physiklaborant': 'Berufe',
  'Chemielaborant': 'Berufe',
  'Biologielaborant': 'Berufe',
  'Radiologe': 'Berufe',
  'Anästhesist': 'Berufe',
  'Chirurg': 'Berufe',
  'Orthopäde': 'Berufe',
  'Kardiologe': 'Berufe',
  'Dermatologe': 'Berufe',
  'Pädiater': 'Berufe',
  'Psychiater': 'Berufe',
  'Urologe': 'Berufe',
  'Gynäkologe': 'Berufe',
  'Neurologe': 'Berufe',
  'Onkologe': 'Berufe',
  'Augenarzt': 'Berufe',
  'Hals-Nasen-Ohren-Arzt': 'Berufe',
  'Zahntechniker': 'Berufe',
  'Podologe': 'Berufe',
  'Orthopädieschuhmacher': 'Berufe',
  'Star Wars': 'Filme/Serien',
  'Der Pate': 'Filme/Serien',
  'Titanic': 'Filme/Serien',
  'Harry Potter': 'Filme/Serien',
  'Der Herr der Ringe': 'Filme/Serien',
  'E.T. – Der Außerirdische': 'Filme/Serien',
  'Jurassic Park': 'Filme/Serien',
  'Avatar – Aufbruch nach Pandora': 'Filme/Serien',
  'Avengers: Endgame': 'Filme/Serien',
  'Vom Winde verweht': 'Filme/Serien',
  'Casablanca': 'Filme/Serien',
  'Der Zauberer von Oz': 'Filme/Serien',
  'Psycho': 'Filme/Serien',
  '2001: Odyssee im Weltraum': 'Filme/Serien',
  'Zurück in die Zukunft': 'Filme/Serien',
  'Pulp Fiction': 'Filme/Serien',
  'Forrest Gump': 'Filme/Serien',
  'Matrix': 'Filme/Serien',
  'Inception': 'Filme/Serien',
  'Interstellar': 'Filme/Serien',
  'Fight Club': 'Filme/Serien',
  'Das Schweigen der Lämmer': 'Filme/Serien',
  'Schindlers Liste': 'Filme/Serien',
  'Die Verurteilten': 'Filme/Serien',
  'Sieben': 'Filme/Serien',
  'GoodFellas – Drei Jahrzehnte in der Mafia': 'Filme/Serien',
  'Der König der Löwen': 'Filme/Serien',
  'Findet Nemo': 'Filme/Serien',
  'Toy Story': 'Filme/Serien',
  'Die Eiskönigin – Völlig unverfroren': 'Filme/Serien',
  'Minions': 'Filme/Serien',
  'Shrek – Der tollkühne Held': 'Filme/Serien',
  'Mickey Mouse': 'Filme/Serien',
  'Donald Duck': 'Filme/Serien',
  'SpongeBob Schwammkopf': 'Filme/Serien',
  'Die Simpsons': 'Filme/Serien',
  'Family Guy': 'Filme/Serien',
  'South Park': 'Filme/Serien',
  'Breaking Bad': 'Filme/Serien',
  'Game of Thrones': 'Filme/Serien',
  'Friends': 'Filme/Serien',
  'The Big Bang Theory': 'Filme/Serien',
  'How I Met Your Mother': 'Filme/Serien',
  'The Office': 'Filme/Serien',
  'Stranger Things': 'Filme/Serien',
  'Squid Game': 'Filme/Serien',
  'The Crown': 'Filme/Serien',
  'Sherlock': 'Filme/Serien',
  'Dr. House': 'Filme/Serien',
  'Grey’s Anatomy': 'Filme/Serien',
  'Emergency Room – Die Notaufnahme': 'Filme/Serien',
  'Lost': 'Filme/Serien',
  'Akte X – Die unheimlichen Fälle des FBI': 'Filme/Serien',
  'Miami Vice': 'Filme/Serien',
  'Magnum, P.I.': 'Filme/Serien',
  'Knight Rider': 'Filme/Serien',
  'Dallas': 'Filme/Serien',
  'Denver-Clan': 'Filme/Serien',
  'Falcon Crest': 'Filme/Serien',
  'Gute Zeiten, schlechte Zeiten': 'Filme/Serien',
  'Tatort': 'Filme/Serien',
  'Polizeiruf 110': 'Filme/Serien',
  'Kommissar Rex': 'Filme/Serien',
  'Derrick': 'Filme/Serien',
  'Ein Colt für alle Fälle': 'Filme/Serien',
  'MacGyver': 'Filme/Serien',
  'Das A-Team': 'Filme/Serien',
  'Baywatch – Die Rettungsschwimmer von Malibu': 'Filme/Serien',
  'Beverly Hills, 90210': 'Filme/Serien',
  'Melrose Place': 'Filme/Serien',
  'Sex and the City': 'Filme/Serien',
  'Desperate Housewives': 'Filme/Serien',
  'Gossip Girl': 'Filme/Serien',
  'One Tree Hill': 'Filme/Serien',
  'O.C., California': 'Filme/Serien',
  'Dawson’s Creek': 'Filme/Serien',
  'Buffy – Im Bann der Dämonen': 'Filme/Serien',
  'Charmed – Zauberhafte Hexen': 'Filme/Serien',
  'Smallville': 'Filme/Serien',
  'Supernatural': 'Filme/Serien',
  'The Vampire Diaries': 'Filme/Serien',
  'Pretty Little Liars': 'Filme/Serien',
  'Gilmore Girls': 'Filme/Serien',
  'Ally McBeal': 'Filme/Serien',
  'Seinfeld': 'Filme/Serien',
  'Frasier': 'Filme/Serien',
  'Cheers': 'Filme/Serien',
  'MAS*H': 'Filme/Serien',
  'I Love Lucy': 'Filme/Serien',
  'Die Addams Family': 'Filme/Serien',
  'Die Munsters': 'Filme/Serien',
  'Bezaubernde Jeannie': 'Filme/Serien',
  'Verliebt in eine Hexe': 'Filme/Serien',
  'Bonanza': 'Filme/Serien',
  'Rauchende Colts': 'Filme/Serien',
  'Star Trek': 'Filme/Serien',
  'Babylon 5': 'Filme/Serien',
  'Battlestar Galactica': 'Filme/Serien',
  'Doctor Who': 'Filme/Serien',
  'Sherlock Holmes': 'Filme/Serien',
  'James Bond': 'Filme/Serien',
  'Indiana Jones': 'Filme/Serien',
  'Mission: Impossible': 'Filme/Serien',
  'Rocky': 'Filme/Serien',
  'Rambo': 'Filme/Serien',
  'Terminator': 'Filme/Serien',
  'Alien': 'Filme/Serien',
  'Predator': 'Filme/Serien',
  'Fluch der Karibik': 'Filme/Serien',
  'Fast & Furious': 'Filme/Serien',
  'Das Imperium schlägt zurück': 'Filme/Serien',
  'Der dunkle Ritter': 'Filme/Serien',
  'Good Will Hunting': 'Filme/Serien',
  'Einer flog über das Kuckucksnest': 'Filme/Serien',
  'Das Leben ist schön': 'Filme/Serien',
  'Der Soldat James Ryan': 'Filme/Serien',
  'Gladiator': 'Filme/Serien',
  'Braveheart': 'Filme/Serien',
  'Der Exorzist': 'Filme/Serien',
  'Shining': 'Filme/Serien',
  'Halloween': 'Filme/Serien',
  'Nightmare – Mörderische Träume': 'Filme/Serien',
  'Freitag der 13.': 'Filme/Serien',
  'Saw': 'Filme/Serien',
  'Der weiße Hai': 'Filme/Serien',
  'Das Fenster zum Hof': 'Filme/Serien',
  'Vertigo – Aus dem Reich der Toten': 'Filme/Serien',
  'Die Vögel': 'Filme/Serien',
  'Lawrence von Arabien': 'Filme/Serien',
  'Ben Hur': 'Filme/Serien',
  'Cleopatra': 'Filme/Serien',
  'Spartacus': 'Filme/Serien',
  'West Side Story': 'Filme/Serien',
  'Mary Poppins': 'Filme/Serien',
  'The Sound of Music': 'Filme/Serien',
  'Grease': 'Filme/Serien',
  'Dirty Dancing': 'Filme/Serien',
  'Flashdance': 'Filme/Serien',
  'Footloose': 'Filme/Serien',
  'Saturday Night Fever': 'Filme/Serien',
  'Staying Alive': 'Filme/Serien',
  'Fame – Der Weg zum Ruhm': 'Filme/Serien',
  'A Star Is Born': 'Filme/Serien',
  'Moulin Rouge!': 'Filme/Serien',
  'La La Land': 'Filme/Serien',
  'Chicago': 'Filme/Serien',
  'Cabaret': 'Filme/Serien',
  'My Fair Lady': 'Filme/Serien',
  'Singin’ in the Rain': 'Filme/Serien',
  'Vier Fäuste für ein Halleluja': 'Filme/Serien',
  'Zwei glorreiche Halunken': 'Filme/Serien',
  'Spiel mir das Lied vom Tod': 'Filme/Serien',
  'Für eine Handvoll Dollar': 'Filme/Serien',
  'Der mit dem Wolf tanzt': 'Filme/Serien',
  'Unversöhnlich': 'Filme/Serien',
  'High Noon – Zwölf Uhr mittags': 'Filme/Serien',
  'Shane': 'Filme/Serien',
  'Rio Bravo': 'Filme/Serien',
  'Der Wilde Westen': 'Filme/Serien',
  'Winnetou': 'Filme/Serien',
  'Old Shatterhand': 'Filme/Serien',
  'Die Olsenbande': 'Filme/Serien',
  'Asterix und Obelix': 'Filme/Serien',
  'Lucky Luke': 'Filme/Serien',
  'Die Schlümpfe': 'Filme/Serien',
  'Biene Maja': 'Filme/Serien',
  'Heidi': 'Filme/Serien',
  'Pinocchio': 'Filme/Serien',
  'Das Dschungelbuch': 'Filme/Serien',
  'Cinderella': 'Filme/Serien',
  'Schneewittchen und die sieben Zwerge': 'Filme/Serien',
  'Dornröschen': 'Filme/Serien',
  'Arielle, die Meerjungfrau': 'Filme/Serien',
  'Die Schöne und das Biest': 'Filme/Serien',
  'Aladdin': 'Filme/Serien',
  'Mulan': 'Filme/Serien',
  'Pocahontas': 'Filme/Serien',
  'Tarzan': 'Filme/Serien',
  'Cars': 'Filme/Serien',
  'Ratatouille': 'Filme/Serien',
  'Wall-E – Der Letzte räumt die Erde auf': 'Filme/Serien',
  'Oben': 'Filme/Serien',
  'Alles steht Kopf': 'Filme/Serien',
  'Coco – Lebendiger als das Leben!': 'Filme/Serien',
  'Chihiros Reise ins Zauberland': 'Filme/Serien',
  'Mein Nachbar Totoro': 'Filme/Serien',
  'Prinzessin Mononoke': 'Filme/Serien',
  'Das wandelnde Schloss': 'Filme/Serien',
  'Akira': 'Filme/Serien',
  'Dragon Ball': 'Filme/Serien',
  'Sailor Moon': 'Filme/Serien',
  'Pokémon': 'Filme/Serien',
  'Neon Genesis Evangelion': 'Filme/Serien',
  'One Piece': 'Filme/Serien',
  'Naruto': 'Filme/Serien',
  'Attack on Titan': 'Filme/Serien',
  'Albert Einstein': 'Berühmte Persönlichkeit',
  'Leonardo da Vinci': 'Berühmte Persönlichkeit',
  'William Shakespeare': 'Berühmte Persönlichkeit',
  'Mahatma Gandhi': 'Berühmte Persönlichkeit',
  'Nelson Mandela': 'Berühmte Persönlichkeit',
  'Marilyn Monroe': 'Berühmte Persönlichkeit',
  'Winston Churchill': 'Berühmte Persönlichkeit',
  'Isaac Newton': 'Berühmte Persönlichkeit',
  'Martin Luther King Jr.': 'Berühmte Persönlichkeit',
  'Steve Jobs': 'Berühmte Persönlichkeit',
  'Michael Jackson': 'Berühmte Persönlichkeit',
  'Elvis Presley': 'Berühmte Persönlichkeit',
  'Charles Darwin': 'Berühmte Persönlichkeit',
  'Julius Caesar': 'Berühmte Persönlichkeit',
  'Napoleon Bonaparte': 'Berühmte Persönlichkeit',
  'Alexander the Great': 'Berühmte Persönlichkeit',
  'Muhammad Ali': 'Berühmte Persönlichkeit',
  'Queen Elizabeth II': 'Berühmte Persönlichkeit',
  'Marie Curie': 'Berühmte Persönlichkeit',
  'Nikola Tesla': 'Berühmte Persönlichkeit',
  'Stephen Hawking': 'Berühmte Persönlichkeit',
  'Oprah Winfrey': 'Berühmte Persönlichkeit',
  'Mother Teresa': 'Berühmte Persönlichkeit',
  'Sigmund Freud': 'Berühmte Persönlichkeit',
  'Pablo Picasso': 'Berühmte Persönlichkeit',
  'Vincent van Gogh': 'Berühmte Persönlichkeit',
  'Ludwig van Beethoven': 'Berühmte Persönlichkeit',
  'Wolfgang Amadeus Mozart': 'Berühmte Persönlichkeit',
  'Frida Kahlo': 'Berühmte Persönlichkeit',
  'Mark Twain': 'Berühmte Persönlichkeit',
  'J.K. Rowling': 'Berühmte Persönlichkeit',
  'George Washington': 'Berühmte Persönlichkeit',
  'Abraham Lincoln': 'Berühmte Persönlichkeit',
  'Franklin D. Roosevelt': 'Berühmte Persönlichkeit',
  'John F. Kennedy': 'Berühmte Persönlichkeit',
  'Barack Obama': 'Berühmte Persönlichkeit',
  'Donald Trump': 'Berühmte Persönlichkeit',
  'Joe Biden': 'Berühmte Persönlichkeit',
  'Adolf Hitler': 'Berühmte Persönlichkeit',
  'Joseph Stalin': 'Berühmte Persönlichkeit',
  'Vladimir Putin': 'Berühmte Persönlichkeit',
  'Mao Zedong': 'Berühmte Persönlichkeit',
  'Kim Jong-un': 'Berühmte Persönlichkeit',
  'Che Guevara': 'Berühmte Persönlichkeit',
  'Fidel Castro': 'Berühmte Persönlichkeit',
  'Dalai Lama': 'Berühmte Persönlichkeit',
  'Pope Francis': 'Berühmte Persönlichkeit',
  'Jesus Christ': 'Berühmte Persönlichkeit',
  'Buddha': 'Berühmte Persönlichkeit',
  'Confucius': 'Berühmte Persönlichkeit',
  'Muhammad': 'Berühmte Persönlichkeit',
  'Socrates': 'Berühmte Persönlichkeit',
  'Plato': 'Berühmte Persönlichkeit',
  'Aristotle': 'Berühmte Persönlichkeit',
  'Galileo Galilei': 'Berühmte Persönlichkeit',
  'Marco Polo': 'Berühmte Persönlichkeit',
  'Christopher Columbus': 'Berühmte Persönlichkeit',
  'Ferdinand Magellan': 'Berühmte Persönlichkeit',
  'Neil Armstrong': 'Berühmte Persönlichkeit',
  'Buzz Aldrin': 'Berühmte Persönlichkeit',
  'Yuri Gagarin': 'Berühmte Persönlichkeit',
  'Elon Musk': 'Berühmte Persönlichkeit',
  'Jeff Bezos': 'Berühmte Persönlichkeit',
  'Mark Zuckerberg': 'Berühmte Persönlichkeit',
  'Bill Gates': 'Berühmte Persönlichkeit',
  'Warren Buffett': 'Berühmte Persönlichkeit',
  'Richard Branson': 'Berühmte Persönlichkeit',
  'Walt Disney': 'Berühmte Persönlichkeit',
  'Stan Lee': 'Berühmte Persönlichkeit',
  'Bruce Lee': 'Berühmte Persönlichkeit',
  'Jackie Chan': 'Berühmte Persönlichkeit',
  'Tom Cruise': 'Berühmte Persönlichkeit',
  'Leonardo DiCaprio': 'Berühmte Persönlichkeit',
  'Brad Pitt': 'Berühmte Persönlichkeit',
  'Angelina Jolie': 'Berühmte Persönlichkeit',
  'Jennifer Aniston': 'Berühmte Persönlichkeit',
  'Keanu Reeves': 'Berühmte Persönlichkeit',
  'Dwayne Johnson': 'Berühmte Persönlichkeit',
  'Will Smith': 'Berühmte Persönlichkeit',
  'Robert Downey Jr.': 'Berühmte Persönlichkeit',
  'Johnny Depp': 'Berühmte Persönlichkeit',
  'Clint Eastwood': 'Berühmte Persönlichkeit',
  'Meryl Streep': 'Berühmte Persönlichkeit',
  'Audrey Hepburn': 'Berühmte Persönlichkeit',
  'Charlie Chaplin': 'Berühmte Persönlichkeit',
  'Frodo Baggins': 'Berühmte Persönlichkeit',
  'Darth Vader': 'Berühmte Persönlichkeit',
  'Yoda': 'Berühmte Persönlichkeit',
  'Luke Skywalker': 'Berühmte Persönlichkeit',
  'Batman': 'Berühmte Persönlichkeit',
  'Superman': 'Berühmte Persönlichkeit',
  'Wonder Woman': 'Berühmte Persönlichkeit',
  'Spider-Man': 'Berühmte Persönlichkeit',
  'Iron Man': 'Berühmte Persönlichkeit',
  'Hulk': 'Berühmte Persönlichkeit',
  'Captain America': 'Berühmte Persönlichkeit',
  'Queen Victoria': 'Berühmte Persönlichkeit',
};
